<?php
/**
 * @file
 * Hides the event field from the add submission and add movie submission form
 * Adds required checkboxes that aren't actually part of the content type
 */

/**
 * Implementation of HOOK_form_FORM_ID_alter()
 */
function bridges_hide_event_form_submission_node_form_alter(&$form, $form_state, $form_id) {
  // hide/disable event dropdown
  $form['field_event']['#access']=FALSE;

  // show event term at top of form so it's clear what's being submitted to
  $default_value_index = $form['field_event'][LANGUAGE_NONE]['#default_value'][0];
  $default_value = $form['field_event'][LANGUAGE_NONE]['#options'][$default_value_index];
  drupal_set_title(t('Create ' . $form['type']['#value'] . ': ' . $default_value));

  // load custom js for form
  $path = drupal_get_path('module', 'bridges_hide_event');
  $form['#attached'] = array
  (
   'js' => array
   (
    'type' => 'file',
    'data' => $path . '/form.js',
  ),
 );

  $form['delivery_pickup'] = array(
    '#type' => 'checkbox',
    '#title' => t("I understand that I am responsible for the timely delivery and pick-up of all works including any necessary shipping arrangements and subsequent costs incurred."),
    '#required' => TRUE,
    '#weight' => 30,
  );

  $form['terms_of_use'] = array(
    '#type' => 'checkbox',
    '#title' => t("I have read and agree to all of the conditions outlined above."),
    '#required' => TRUE,
    '#weight' => 30,
  );

  // artworks are set to unlimited so we get the "add more" button
  // but we want to limit to [2 for Bridges/JMM, 5 for ICERM], so hide the button when we get to 8
  // set to N - 1
  if (isset($form['field_artwork']['und']['#max_delta']) && $form['field_artwork']['und']['#max_delta'] == 4) {
    $form['field_artwork']['und']['add_more']['#prefix'] = '<div style="display:none">';
    $form['field_artwork']['und']['add_more']['#suffix'] = '</div>';
  }

}


function bridges_hide_event_form_movie_submission_node_form_alter(&$form, $form_state, $form_id) {
  // hide/disable event dropdown
  $form['field_event']['#access']=FALSE;

  // show event term at top of form so it's clear what's being submitted to
  $default_value_index = $form['field_event'][LANGUAGE_NONE]['#default_value'][0];
  $default_value = $form['field_event'][LANGUAGE_NONE]['#options'][$default_value_index];
  drupal_set_title(t('Create ' . $form['type']['#value'] . ': ' . $default_value));

  // load custom js for form
  $path = drupal_get_path('module', 'bridges_hide_event');
  $form['#attached'] = array
  (
    'js' => array
    (
      'type' => 'file',
      'data' => $path . '/form.js',
    ),
  );

  $form['delivery_pickup'] = array(
    '#type' => 'checkbox',
    '#title' => t("I understand that I am responsible for the timely delivery and pick-up of all works including any necessary shipping arrangements and subsequent costs incurred."),
    '#required' => TRUE,
    '#weight' => 30,
  );

  $form['terms_of_use'] = array(
    '#type' => 'checkbox',
    '#title' => t("I have read and agree to all of the conditions outlined above."),
    '#required' => TRUE,
    '#weight' => 30,
  );

}

function bridges_hide_event_form_fashion_submission_node_form_alter(&$form, $form_state, $form_id) {
  // hide/disable event dropdown
  $form['field_event']['#access']=FALSE;

  // show event term at top of form so it's clear what's being submitted to
  $default_value_index = $form['field_event'][LANGUAGE_NONE]['#default_value'][0];
  $default_value = $form['field_event'][LANGUAGE_NONE]['#options'][$default_value_index];
  drupal_set_title(t('Create ' . $form['type']['#value'] . ': ' . $default_value));

  // load custom js for form
  $path = drupal_get_path('module', 'bridges_hide_event');
  $form['#attached'] = array
  (
    'js' => array
    (
      'type' => 'file',
      'data' => $path . '/form.js',
    ),
  );

  $form['delivery_pickup'] = array(
    '#type' => 'checkbox',
    '#title' => t("I understand that I am responsible for the timely delivery and pick-up of all works including any necessary shipping arrangements and subsequent costs incurred."),
    '#required' => TRUE,
    '#weight' => 30,
  );

  $form['terms_of_use'] = array(
    '#type' => 'checkbox',
    '#title' => t("I have read and agree to all of the conditions outlined above."),
    '#required' => TRUE,
    '#weight' => 30,
  );

  // fashion items are set to unlimited so we get the "add more" button
  // but we want to limit to 8, so hide the button when we get to 8
  if (isset($form['field_fashion_items']['und']['#max_delta']) && $form['field_fashion_items']['und']['#max_delta'] == 7) {
    $form['field_fashion_items']['und']['add_more']['#prefix'] = '<div style="display:none">';
    $form['field_fashion_items']['und']['add_more']['#suffix'] = '</div>';
  }

  // Similar for collection images
  if (isset($form['field_collection_images']['und']['#max_delta']) && $form['field_collection_images']['und']['#max_delta'] == 1) {
    $form['field_collection_images']['und']['add_more']['#prefix'] = '<div style="display:none">';
    $form['field_collection_images']['und']['add_more']['#suffix'] = '</div>';
  }
}
