<?php
/**
 * @file
 * Creates autotitle tokens for use in submission titles
 */

/**
 * Implementation of hook_token_info()
 */
function bridges_autotitle_token_info() {
  // Define token value, autotitle is the token will be used as [node:autotitle]
  $node['autotitle'] =  array(
    'name' => t("Automatic submission title"),
    'description' => t("Use extended name if provided, otherwise use first and last name"),
  );
  // Define token value, fashion_autotitle is the token will be used as [node:fashion_autotitle]
  $node['fashion_autotitle'] =  array(
    'name' => t("Automatic submission title (fashion)"),
    'description' => t("Use brand name if selected, otherwise use designer name"),
  );

  // Return associative array of tokens & token types
  return array(
    'tokens' => array(
      'node' => $node,
    ),
  );
}

/**
 * Implements hook_tokens().
 */
function bridges_autotitle_tokens($type, $tokens, array $data = array(), array $options = array()) {
  $replacements = array();

  // Check if token type is node
  if($type == 'node'){
    $node_wrapper = entity_metadata_wrapper('node', $data['node']);
    foreach ($tokens as $name => $original) {
      switch ($name) {
        // Check token is autotitle
        case 'autotitle':
          $extended_name = $node_wrapper->field_extended_name->value();
          $first_name = $node_wrapper->field_first_name->value();
          $last_name = $node_wrapper->field_last_name->value();

          $replacements[$original] = empty($extended_name) ? $first_name . " " . $last_name : $extended_name;
          break;
        case 'fashion_autotitle':
          $use_brand_name = $node_wrapper->field_use_brand_name->value();
          $name_designer = $node_wrapper->field_name_designer->value();
          $name_brand = $node_wrapper->field_name_brand->value();

          $replacements[$original] = $use_brand_name ? $name_brand : $name_designer;
          break;
      }
    }
  }
  return $replacements;
}
